[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_PUBLIC_TENSORFLOW_JS_VERSION = "4.17.0"
  NPM_CONFIG_PRODUCTION = "false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs" 